-- CREATE TABLE IF NOT EXISTS users(
--     id SERIAL PRIMARY KEY, 
--     first_name VARCHAR(100) NOT NULL,
--     last_name VARCHAR(100) NOT NULL,
--     username VARCHAR,
--     password VARHCAR(100) NOT NULL
-- );